networks:
  tests:
    driver: bridge

services:
  local-testing:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - pennsievedb-dbmigrate
    networks:
      - tests

  pennsievedb-dbmigrate:
    image: pennsieve/pennsievedb:V20241120161735-seed
    restart: always
    ports:
      - "5432:5432"
    networks:
      - tests
