FROM golang:1.23-alpine

WORKDIR /test

ENV CGO_ENABLED=0

COPY go.mod .
RUN ["go", "mod", "download"]

COPY pkg pkg
COPY internal internal
RUN ["go", "mod", "tidy"]

CMD ["go", "test", "-v", "./..."]
